# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgIdjmuRvv7Ps1XD9Ev2XS_O1BJE66gE

Programa funcional Grupo H.
Rivera Klee.
Vasquez Carranza.
"""

import os

class Programa:
    def main():
        estaciones = {
            51: 'Estación Javier',
            61: 'Estación Trébol',
            71: 'Estación Don Bosco',
            82: 'Estación Plaza Municipal'
        }

        rutas = {
            (51, 61): 39,
            (51, 71): 18,
            (71, 82): 23,
            (61, 51): 8,
            (82, 51): 42
        }

        boletos_vendidos = {}
        for ruta, _ in rutas.items():
            boletos_vendidos[ruta] = 0
        recaudacion = 0

        while True:
            print("\n1. Ver estaciones existentes\n2. Comprar boleto\n3. Reportes\n4. Salir")
            while True:
                try:
                    opcion = int(input("Que gestión desea realizar? : "))
                    if opcion not in [1, 2, 3, 4]:
                        raise ValueError
                    break
                except ValueError:
                    print("Por favor, ingrese un numero 1 y 4.")

            if opcion == 1:
                print("\nEstaciones disponibles:")
                for codigo, estacion in estaciones.items():
                    print(f"{codigo}: {estacion}")
                print("\nRutas:")
                for ruta, distancia in rutas.items():
                    print(f"De {estaciones[ruta[0]]} a {estaciones[ruta[1]]} hay {distancia} km")
                input("\nOprime enter para continuar...")
                os.system('cls')

            elif opcion == 2:
                while True:
                    try:
                        partida = int(input("\nNúmero de estación de partida: "))
                        if partida not in estaciones:
                            raise ValueError
                        break
                    except ValueError:
                        print("Por favor ingrese un número de estación válido.")
                while True:
                    try:
                        destino = int(input("Número de estación de destino: "))
                        if destino not in estaciones:
                            raise ValueError
                        break
                    except ValueError:
                        print("Por favor, ingrese un número de estación válido.")
                if (partida, destino) not in rutas:
                    print("Ruta inexistente.")
                    continue
                nombre = input("Cual es tu nombre?: ")
                while True:
                    try:
                        edad = int(input("Cuantos años tienes?: "))
                        if edad < 0:
                            raise ValueError
                        break
                    except ValueError:
                        print("Por favor, ingrese una edad válida.")
                embarazada = input("¿Está embarazada? (si o no): ") == 'si'
                distancia = rutas[(partida, destino)]
                if embarazada:
                    precio = 0
                else:
                    precio = 1.5 if distancia <= 8 else 1.5 + (distancia - 8) * 0.25
                    if 15 <= edad <= 25:
                        precio *= 0.75
                precio = round(precio, 2)
                tiempo = distancia / 20
                horas, resto = divmod(tiempo, 1)
                minutos = resto * 60
                print(f"\nEstación de partida: {estaciones[partida]}")
                print(f"Estación de destino: {estaciones[destino]}")
                print(f"Precio del boleto: Q{precio}")
                print(f"Tiempo aproximado de viaje: {int(horas)} horas y {int(minutos)} minutos")

                boletos_vendidos[(partida, destino)] += 1
                recaudacion += precio
                input("\nOprima enter para continuar...")
                os.system('cls')

            elif opcion == 3:
                print("\nBoletos vendidos en cada ruta:")
                for ruta, boletos in boletos_vendidos.items():
                    print(f"De {estaciones[ruta[0]]} para {estaciones[ruta[1]]}: {boletos}")
                print(f"\nGanancias percibidas: Q{round(recaudacion, 2)}")
                input("\nOprima Enter para continuar...")
                os.system('cls')

            elif opcion == 4:
                break

Programa.main()